#!/bin/sh
set -e
# Automatically added by dh_installinit
if [ -x "/etc/init.d/gvpn-daemon" ]; then
	update-rc.d gvpn-daemon defaults >/dev/null
	if [ -x "`which invoke-rc.d 2>/dev/null`" ]; then
		invoke-rc.d gvpn-daemon start || exit $?
	else
		/etc/init.d/gvpn-daemon start || exit $?
	fi
fi
# End automatically added section
